apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: misconfigured-secret
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: nonexistent-store
    kind: SecretStore
  target:
    name: misconfigured-secret
    creationPolicy: Owner
  data:
  - secretKey: username
    remoteRef:
      key: invalid/path/to/secret
      property: username
  - secretKey: password 
    remoteRef:
      key: invalid/path/to/secret
      property: password
