apiVersion: apps/v1
kind: Deployment
metadata:
  name: missing-configmap-deployment
  labels:
    app: missing-configmap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: missing-configmap
  template:
    metadata:
      labels:
        app: missing-configmap
    spec:
      containers:
      - name: missing-configmap
        image: nginx:latest
        ports:
        - containerPort: 8080
          protocol: TCP
        volumeMounts:
        - name: missing-configmap
          mountPath: /etc/nginx/conf.d
      volumes:
      - name: missing-configmap
        configMap:
          name: missing-configmap
