apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "6"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"busybox"},"name":"busybox-deployment","namespace":"kubecost"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"busybox"}},"template":{"metadata":{"labels":{"app":"busybox"}},"spec":{"containers":[{"command":["sleep","infinity"],"image":"busybox:latest","name":"busybox"}],"serviceAccount":"missing"}}}}
  creationTimestamp: "2025-04-09T12:53:08Z"
  generation: 10
  labels:
    app: busybox
  name: busybox-deployment
  namespace: kubecost
  resourceVersion: "40704109"
  uid: 58b5f3d4-1fb2-4a99-979b-d9ab778911d9
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: busybox
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: busybox
    spec:
      containers:
      - command:
        - sleep
        - infinity
        image: busybox:latest
        imagePullPolicy: Always
        name: busybox
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-04-23T01:50:05Z"
    lastUpdateTime: "2025-04-23T01:50:05Z"
    message: ReplicaSet "busybox-deployment-7f49499c8" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2025-04-23T02:14:11Z"
    lastUpdateTime: "2025-04-23T02:14:11Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 10
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
