apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-pod
  name: nginx-pod
spec:
  containers:
  - image: nginx
    name: nginx-pod
    resources: {}
    volumeMounts:
    - mountPath: /test
      name: test
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: test
    emptyDir: {}
status: {}
