apiVersion: apps/v1
kind: Deployment
metadata:
  name: missing-serviceaccount-deployment
  labels:
    app: missing-serviceaccount
spec:
  replicas: 1
  selector:
    matchLabels:
      app: missing-serviceaccount
  template:
    metadata:
      labels:
        app: missing-serviceaccount
    spec:
      serviceAccount: default
      containers:
      - name: missing-serviceaccount
        image: nginx:latest
        ports:
        - containerPort: 8080
